"""migrate table

Revision ID: b8560a6a4caf
Revises: 
Create Date: 2020-09-23 17:36:59.878687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8560a6a4caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('crust', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizzas')
    # ### end Alembic commands ###
